[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"

[tool.poetry]
authors = ["Leandro"]
description = "Nada"
name = "tse_importador"
version = "1.0"