# Generated by Django 5.0.6 on 2024-06-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filiado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloEleitor', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('dataFiliacao', models.DateTimeField()),
                ('uf', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('zona', models.IntegerField()),
                ('situacao', models.CharField(max_length=30)),
                ('pendenciaComunicacao', models.BooleanField(default=False)),
                ('nome_completo', models.CharField(max_length=300)),
                ('nome_social', models.CharField(max_length=300)),
                ('data_nascimento', models.DateTimeField(blank=True, null=True)),
                ('sexualidade', models.CharField(blank=True, max_length=50, null=True)),
                ('raca', models.CharField(blank=True, max_length=50, null=True)),
                ('pcd', models.BooleanField(default=False)),
                ('local_residencia', models.CharField(blank=True, max_length=50, null=True)),
                ('local_exercicio', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
