# Generated by Django 5.0.6 on 2024-09-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiado',
            name='cep',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='filiado',
            name='cpf',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='filiado',
            name='data_atualizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filiado',
            name='data_inscricao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filiado',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='filiado',
            name='endereco_residencial',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='filiado',
            name='municipio_onde_vota',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='filiado',
            name='nome_mae',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='filiado',
            name='ocupacao',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='filiado',
            name='reponsavelFiliacao',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='filiado',
            name='rg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='filiado',
            name='secao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filiado',
            name='telefoneComDDD',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='filiado',
            name='whatsAppComDDD',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='filiado',
            name='municipio',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
