# Generated by Django 5.0.6 on 2024-09-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiados', '0002_filiado_cep_filiado_cpf_filiado_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiado',
            name='municipio',
            field=models.CharField(default='Desconhecido', max_length=50),
        ),
    ]
