# Generated by Django 5.0.6 on 2024-09-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiados', '0004_alter_filiado_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiado',
            name='municipio',
            field=models.CharField(default='Desconhecido', max_length=50, null=True),
        ),
    ]
