# Generated by Django 5.0.6 on 2025-03-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiados', '0005_alter_filiado_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiado',
            name='etnia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='filiado',
            name='profissao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
