from enum import Enum

class regiao_administrativa(Enum):
    PLANO_PILOTO = {numero:1, nome: "Plano Piloto"},
    GAMA = {numero:2, nome: "Gama"},
    TAGUATINGA = {numero: 3, nome: "Taguatinga"},
    BRAZLANDIA = {numero: 4, nome: "Brazlândia"},
    SOBRADINHO = {numero: 5, nome: "Sobradinho"},
    PLANALTINA = {numero: 6, nome: "Planaltina"},
    PARANOA = {numero: 7, nome: "Paranoá"},
    NUCLEO_BANDEIRANTE = {numero: 8, nome: "Núcleo Bandeirante"},
    CEILANDIA = {numero: 9, nome: "Ceilândia"},
    GUARA = {numero: 10 , nome:"Guará"}, 
    CRUZEIRO = {numero: 11, nome: "Cruzeiro"},
    SAMAMBAIA = {numero: 12, nome: "Samambaia"},
    SANTA_MARIA = {numero: 13, nome: "Santa Maria"},
    SAO_SEBASTIAO = {numero: 14, nome: "São Sebastião"},
    RECANTO_DAS_EMAS = {numero: 15 , nome: "Recanto das Emas"},
    LAGO_SUL = {numero: 16, nome: "Lago Sul"},
    RIACHO_FUNDO = {numero: 17, nome: "Riacho Fundo"},
    LAGO_NORTE = {numero: 18, nome: "Lago Norte"},
    CANDANGOLANDIA = {numero: 19, nome: "Candangolândia"},
    AGUAS_CLARAS = {numero: 20, nome: "Águas Claras"},   
    RIACHO_FUNDO_II = {numero: 21, nome: "Riacho Fundo II"},
    SUDOESTE_OCTOGONAL = {numero: 22, nome: "Sudoeste/Octogonal"},

    VARJAO = {numero: 23, nome: "Varjão"},
    PARK_WAY = {numero: 24, nome: "Park Way"},
    SCIA = {numero: 25, nome: "SCIA"},
    SOBRADINHO_II = {numero: 26, nome: "Sobradinho II"},
    JARDIM_BOTANICO = {numero: 27, nome: "Jardim Botânico"},

    ITAPOA = {numero: 28, nome: "Itapoã"},
    SIA = {numero: 29, nome: "SIA"},
    VINCENTE_PIRES = {numero: 30, nome: "Vincente Pires"},
    FERCAL = {numero: 31, nome: "Fercal"},
    SOL_NASCENTE_POR_DO_SOL = {numero:32 , nome: "Sol Nascente/Pôr do Sol"},
    ARNIQUEIRA = {numero: 33, nome: "Arniqueira"},
    ARAPOANGA = {numero: 34, nome: "Arapoanga"},
    AGUA_QUENTE =   {numero:35, nome: "Água Quente"}, 
    pass
