on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: gotechnies/alpine-ssh:latest
    steps:
      - name: Checkout tag
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}  # Faz checkout da tag que disparou a pipeline
      - name: Step
        uses: docker://ghcr.io/OWNER/IMAGE_NAME
      - name: Add SSH Private Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: SSH into OCI Instance
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} opc@<IP_PUBLICO_DA_INSTANCIA> << 'EOF'
          # Comandos que você deseja executar na instância OCI
          echo "Conectado à instância OCI"
          hostname
          EOF
